# Generated by Django 5.0.1 on 2024-03-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_forgotpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=999)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
    ]
