# Generated by Django 5.0.1 on 2024-03-10 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_contact'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
