# Generated by Django 5.0.1 on 2024-04-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_contact_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Fish', 'Fish'), ('Rabbit', 'Rabbit'), ('Gunniepig', 'Gunniepig'), ('Shelters', 'Shelters'), ('Medicines', 'Medicines')], max_length=100),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=30)),
                ('pid', models.IntegerField()),
            ],
            options={
                'db_table': 'cart_table',
                'unique_together': {('mail', 'pid')},
            },
        ),
        migrations.CreateModel(
            name='Cartmultipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=30)),
                ('pid', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'cartmultipleptod_table',
                'unique_together': {('mail', 'pid')},
            },
        ),
    ]
