# Generated by Django 5.0.1 on 2024-04-27 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='ColdCoffee',
        ),
    ]
